name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.23.x
        platform:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Run tests
        run: |
          go test -v -coverprofile coverage.out -covermode atomic ./... 
      - name: Publish coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: --snapshot --skip-publish
