name: Release (Production)

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '**/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.23.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Run tests
        run: |
          go test ./... -coverprofile coverage.out

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: 
      - test
    env:
      CGO_ENABLED: 0
      TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v2
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_GHCR_PAT }}
          registry: ghcr.io
      - name: Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable experimental docker features
        run: |
          mkdir -p ~/.docker/ && \
          echo '{"experimental": "enabled"}' > ~/.docker/config.json
      - name: Create manifest for version
        run: |
          export DH_TAG=$(git tag --points-at HEAD | sed 's/^v*//')
          docker manifest create \
            todd2982/watchtower:$DH_TAG \
            todd2982/watchtower:amd64-$DH_TAG \
            todd2982/watchtower:i386-$DH_TAG \
            todd2982/watchtower:armhf-$DH_TAG \
            todd2982/watchtower:arm64v8-$DH_TAG
          docker manifest create \
            ghcr.io/todd2982/watchtower:$DH_TAG \
            ghcr.io/todd2982/watchtower:amd64-$DH_TAG \
            ghcr.io/todd2982/watchtower:i386-$DH_TAG \
            ghcr.io/todd2982/watchtower:armhf-$DH_TAG \
            ghcr.io/todd2982/watchtower:arm64v8-$DH_TAG
      - name: Annotate manifest for version
        run: |
          for REPO in '' ghcr.io/ ; do
          
          docker manifest annotate \
            ${REPO}todd2982/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}todd2982/watchtower:i386-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch 386
          
          docker manifest annotate \
            ${REPO}todd2982/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}todd2982/watchtower:armhf-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm
      
          docker manifest annotate \
            ${REPO}todd2982/watchtower:$(echo $TAG | sed 's/^v*//') \
            ${REPO}todd2982/watchtower:arm64v8-$(echo $TAG | sed 's/^v*//') \
            --os linux \
            --arch arm64 \
            --variant v8
            
            done
      - name: Create manifest for latest
        run: |
          docker manifest create \
            todd2982/watchtower:latest \
            todd2982/watchtower:amd64-latest \
            todd2982/watchtower:i386-latest \
            todd2982/watchtower:armhf-latest \
            todd2982/watchtower:arm64v8-latest
          docker manifest create \
            ghcr.io/todd2982/watchtower:latest \
            ghcr.io/todd2982/watchtower:amd64-latest \
            ghcr.io/todd2982/watchtower:i386-latest \
            ghcr.io/todd2982/watchtower:armhf-latest \
            ghcr.io/todd2982/watchtower:arm64v8-latest
      - name: Annotate manifest for latest
        run: |
          for REPO in '' ghcr.io/ ; do

          docker manifest annotate \
            ${REPO}todd2982/watchtower:latest \
            ${REPO}todd2982/watchtower:i386-latest \
            --os linux \
            --arch 386
      
          docker manifest annotate \
            ${REPO}todd2982/watchtower:latest \
            ${REPO}todd2982/watchtower:armhf-latest \
            --os linux \
            --arch arm
            
          docker manifest annotate \
            ${REPO}todd2982/watchtower:latest \
            ${REPO}todd2982/watchtower:arm64v8-latest \
            --os linux \
            --arch arm64 \
            --variant v8

          done
      - name: Push manifests to Dockerhub
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN && \
            docker manifest push todd2982/watchtower:$(echo $TAG | sed 's/^v*//') && \
            docker manifest push todd2982/watchtower:latest
      # - name: Push manifests to GitHub Container Registry
      #   env:
      #     DOCKER_USER: ${{ secrets.BOT_USERNAME }}
      #     DOCKER_TOKEN: ${{ secrets.BOT_GHCR_PAT }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_TOKEN ghcr.io && \
      #       docker manifest push ghcr.io/todd2982/watchtower:$(echo $TAG | sed 's/^v*//') && \
      #       docker manifest push ghcr.io/todd2982/watchtower:latest

  # renew-docs:
  #   name: Refresh pkg.go.dev
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Pull new module version
  #     uses: andrewslotin/go-proxy-pull-action@0ef95ea50ab6c03f2f095a5102bbdecad8fd7602 #master@2022-10-14

  
  

  
